language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository

branches:
  except:
  - /^v\d$/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: ./gradlew ciPerformRelease -s
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false

env:
  global:
    - secure: EK9XCJRcFZ0u+jIlCUR09la+e7vhdEj4NIyuK1Tou9nCgg9OZF04E7Qu60y2TmcyOddxWXOtAPjjPyvtlRo7oGJZ2plvZ2FKl3y9p/v5N8may5V+L92EdGT9ldP7+u5jjzKERZhb5PXITBNJ2Owfwb8ex3XrmyPyL9pQnZYiHNW7faehdGpsx4rEJ8uGoJgNomjiWzlgglPCbzaCQcnD+GHOZvecVuQICv7k1+4cmJcV7Xt5MY1mwX0l/fqQSTgzyN3h6TpujciEQ5KKggQP4A/XXCFRGdlxDrhojh3Q4/R8cGsvaxgSA363CXEPwR+8pBjivSJogpbWmcHsMNVz82Ejoi33m/UKny2lFN1A88fsN5KPSuz3dCqsOy/phUq74jnZ0NHUA2B+f+Uy9r/42MWxoTeiDnq8b3T/zCYXhXLW2diJri/UIvCp7bsB4DnsAKv0tGtufROFAMtZw937RuLvuiBZJbliW/4r70pBL2/i5n90PwfUiXGljqsLpGlcBWYldStX22JJE0gS3VRRzPs1sv2YOb9gpDqnqxy6GA7Hm59mxHY2I0BTf5HWGxGyX7kFB2PTrOKkr/bTdIZyxe45DZYAKAhwxJf//UrQAPK33g1ysJ4t4os4pPwg9/+8x7HO9dPH+O917g3bWC9RuLdOjuKRt1YhWF6VyBQd1q4=
    - secure: WKgEDUZxz4GTS8KPjgigZUIgXcoEZJ9dK7b0PzfoJvj7BiVyz+1JoBOhB/k0MSelxXTGDHrp/BxwU9VXQ3mdfnEjwfDLlVtapowxs4cr2XOBXh/J1y0bYe67Y6Bvn2XS+ICg7OJqf07KYDAtBG/mxDVKUfeMGlQGbdkU2E+B0EOUgKpdu4ZD0Q8O/K9V0ohH8vjM6oWUXRMsUdYddFpD3LKbMonuL28FT9cjb6+C8Tjh0IIHiClsSnLgfvNBlhrFYNdO9RnVUERUGaU30BoCCYlzRmSgVlIWWBgj1GDR9Eg+beRGgpjrIWZ/WksBBt+OzM9onUKPV2MStfYrjr9JkdeFNRmJ+elhPyBOXvTCkkVe5NDWBTmp+OQZGUlvij9Yigi5Cw+dIgf7uZjqKyR+ExJxmp17+XbIGaSxauNlhR4XHC9iY23wG8fX5Ee8QEKCbK4dm4Kj5PWshHxWgbGWV2/+dqHpNjJhh3YYqKBHMQZOhbvdoALoNUbJlXCK0uRWAylCyXneZxALATZh9gqbObavd5t6CAur8tWDUnltJk7AXstPglFmpwGLPmZY3RyyLAGakdePLQwgYc+xTmxlWzBUySaa6Qjdre/zDvGXTOeXkbcF7TCgDkec+L0p9Z+l3iIYf7QnplZRCpFtgtZIjSPM5lQiPoPPBKyaWpQiMPk=
    - secure: v4NBEq3PddgM2DjEbuZgkwpsByba9GJBVEPBI+WTii9sW3rL4uOTZWbiOJoc/dVymWEgeJ+adj2L/Jss1H1JFkPQYVj7LT+bnprw0ExZNWeswcKqPyVOXXTPX61ynd/sAYjAU5a/xiP+tGwnAXSZfht/pbnaRq3/4JwsztPkhA1Pqsyx/44bYzmKlbVteUdVGGjsR9kYwAlK7TDS5ELPIMSPYUrbD+btEOwu8OWz634pUU7HaD8UD8WHFFVTMk6T/awskVCjiFNRNvUO9VNQsk6+SMo8etaaRF3ZLCzkyoZDZyBvu45UnsjtfO6MI2eYSErwqXfvTInCU75AVBeWgw2JoG64FKAj8pNLLaB5nY+8dfdq0tJW6I0EUuX+EbEUqwSZ5wBvzHXch1jHxj1Z8RuuHjVsFAZh/6ySHW+kqI2QHWRNYch+gbYJevhQ0MO5AN025vbsmbxbH5ZZtlhHAEuUgN7OC7+BCAk1HQB7Xjag6/ndfw7YrbNwwYOhIR3373Y3lbiAh+YjuR7XCL89fCC4mQBd4+M4ecgscjtpKDJyRcwyxuGTRZKLqK5QiwPL2O6eJBDoY7+VgpWS1DvoouJdSlnUx//zWMt9aKipDbHKqyfdLrgdZBRpgFdEX8ZS6XI7NwgxvWAaBKXrMuRRNvRIWg1z8wRvrmE2JhEA8rM=
    - secure: kXSiNfxCv7JBBiqaEHYIqt+36OPaR7k4rkopc2i/TLWfHqhCaxV2yLvbk0nnLBSzkvWCL5bICyxVwkAZNDShKKGj2XpDbACM9J3KGFNA/wtbdjZcpHuMerhqSUFAzdnZ9QMqnOCd1b974ZbSEToZ4bi8Ed8pkG9QG1XNONBWXgUgWaxwj1koS4HVFhC/w5UFHjlsG/rS3evvazxwtRM9+poInyrd5cNdnzSF1gvyAVToCltgXuhPF3D7Ig2XMBLP4g2DRQRPfR296Vstwj3HxbjZccTL0ncfj53T6i2h0IjrrgyAUuSaN78/f1BJnVnvJ4fwpudhtCyMZNDFIWrlaRDkuXq8qx/vKzHMKVItymJireNJfVLStF0VYAa6I8D8ouyDaR1o5R0KWYCK5CO4/iu2ABNbKVxDwOV7yktWGttmz1pybjPXxqhGgHez2sxnp2d2Z9SsHEThFIoIuUh+vIpi6S//TQJ6g5lhsptPhHGkbG6f8fLkZJmsqzrptGm/KZv5abS4eQ8Ceks4+/YYiMoNfFnJojZyJxkxZ0xzi84sk3IbM/2A3qDzFRUf7qdaz3av07TRlJ1oXHxya+ZJYE/w8Roe0XTomYjZ8e1BbUPBp+1ZYJN25PP92/JSGlQ50QqmCghLMaamLPrfwjLXib5oZIXGo1D9sJ7XQ2fq6FY=
